services:


  nginx:
    container_name: foodgram_proxy
    build:
      context: ..
      dockerfile: infra/Dockerfile
    image: foodgram_proxy
    ports:
      - "8090:80"
    volumes:
    - ../docs:/var/www/docs:ro
    - ../backend/collected_static:/var/www/static:ro
    - ../backend/media:/var/www/media
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
    container_name: foodgram_backend
    env_file:
      - ../.env
    volumes:
      - ../backend/collected_static:/app/collected_static
      - ../backend/media:/app/media
      - ../backend:/app
      - ../data:/app/data
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:16
    container_name: foodgram_db
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
    backend_static:
    backend_media:
    pgdata:
