services:

  frontend:
    container_name: foodgram_frontend
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    container_name: foodgram_proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/build:/usr/share/nginx/html:ro
      - ../docs/:/usr/share/nginx/html/api/docs:ro
      - ../backend/collected_static:/var/www/static
      - ../backend/media:/var/www/media
    depends_on:
      - backend
      - frontend


  backend:
    build:
      context: ../backend
    container_name: foodgram_backend
    env_file:
      - ../.env
    volumes:
      - ../backend/collected_static:/app/collected_static
      - ../backend/media:/app/media
      - ../backend:/app
      - ../data:/app/data
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:16
    container_name: foodgram_db
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  frontend_build:
  backend_static:
  backend_media:
  pgdata:
